#!/bin/bash
#SBATCH --job-name="dsprites_400_double"
#SBATCH --time=15:00:00
#SBATCH --mem-per-cpu=4GB
#SBATCH --cpus-per-task=2
#SBATCH --partition=gpu
#SBATCH --gres=gpu:tesla:1
module load python/3.10.10
module load cuda/11.8
source ../../diffusion/bin/activate
python --version

srun python dsprites_gfn.py --config ../configs/dsprites_fixed_double.yaml --device 0 --dynamics true --epochs 400 --run_name dsprites_400_double
