#!/bin/bash
#SBATCH --job-name="dsprites_500_ref"
#SBATCH --time=20:00:00
#SBATCH --mem-per-cpu=4GB
#SBATCH --cpus-per-task=2
#SBATCH --partition=gpu
#SBATCH --gres=gpu:tesla:1
module load python/3.10.10
module load cuda/11.8
source ../../diffusion/bin/activate
python --version

srun python dsprites_gfn.py --config ../configs/dsprites_gfn_dynamics_em.yaml --device 0 --dynamics true --epochs 500 --run_name dsprites_500_ref
