#!/bin/bash
#SBATCH --job-name="gfn_fixed_same"
#SBATCH --time=15:00:00
#SBATCH --mem-per-cpu=4GB
#SBATCH --cpus-per-task=2
#SBATCH --partition=gpu
#SBATCH --gres=gpu:tesla:1
module load python/3.10.10
module load cuda/11.8
source ../../diffusion/bin/activate
python --version

srun python diffusion_gfn.py --config ../configs/diffusion_fixed_same.yaml --device 0 --dynamics true --epochs 400 --run_name gfn_fixed_same_400 --n_children 2 --seed 5
