# Data
data_batch_size: 128
data_size: 32
data_min_scale: 0
data_holdout_xy_mode: True
data_holdout_xy_nonmode: False
data_holdout_xy_shape: False
data_holdout_xy_mode_color: True
data_holdout_shape_color: True

# VAE
num_vae_updates: 10000
vae_batch_size: 256

# Shared
dim_z: 32
vocab_size: 24
min_w_length: 1
max_w_length: 7

save_prefix: 'em' # Prefix for the saved model files.
save_checkpoint_every: 100000 # How often to save checkpoints (in number of updates)
create_plots_every: 50000 # How often to create plots (in number of updates)

# Reward
score_weight: 1
decodability_weight: 1
length_penalty: 0
min_log_reward: -80

# Discretizer
discretizer_dim_h: 1024
discretizer_num_layers: 3

# Flow models
flow_dim_h: 1024
flow_num_layers: 3

# M-Model
m_model_dim_h: 256
m_model_num_layers: 3
m_model_num_w_embedding_layers: 1

# Training
lr_discretizer: 0.0001
lr_flows: 0.0001
lr_m_step: 0.0001
p_explore_discretizer: .1

# Replay buffer
replay_buffer_inv_freq_sequence: true
replay_buffer_inv_freq_token: true
e_step_batch_size: 1024
m_step_batch_size: 256

e_step_buffer_size: 100000
e_step_start_rollouts: 1024
e_step_buffer_update_interval: 100
e_step_update_rollouts: 256

m_step_buffer_size: 10000
m_step_start_rollouts: 1024
m_step_buffer_update_interval: 100
m_step_update_rollouts: 256

# Images
discretizer_encoder_dim_h: 64
m_model_patch_size: 8
m_model_use_mu_as_z0: true
m_model_sd_model_num_layers: 3
m_model_nhead: 8
m_model_dim_feedforward: 256
m_model_num_encoder_layers: 2
m_model_num_decoder_layers: 2

# Dynamics model
directional_dynamics: true
z0_dependent_forward: false
z0_dependent_backward: true
t_dependent_forward: false
t_dependent_backward: true
z0_dependent_discretizer: false
attractor_sd: 0.025
dynamics_dim_h: 512
dynamics_num_layers: 3
max_mean: 0.25
max_sd: .2
min_sd: 0.001
num_steps: 20

p_sleep_phase: 0.1
p_add_exploration_trajectory: 0.3
lr_dynamics: .0001

# EM
start_e_steps: 0 # number of e-steps to start with, ignoring all other conditions
min_e_steps: 10000 # number of e-steps to perform before checking loss-based conditions
max_e_steps: 10000 # If number of e-steps exceeds this, switch to M-step regardless of loss-based conditions.
num_m_steps: 2500
m_step_substrings: true