attractor_sd: 0.025
contrasts_weight: 1.0
create_plots_every: 50000
decodability_weight: 1
dim_t: 10
dim_z: 32
directional_dynamics: true
discretizer_dim_h: 1024
discretizer_encoder_dim_h: 64
discretizer_fixed_backward_policy: false
discretizer_model: mlp
discretizer_num_layers: 3
discretizer_objective: tb
dynamics_dim_h: 512
dynamics_num_layers: 3
e_loss_improvement_rate: null
e_loss_relaxation_rate: null
e_step_batch_size: 1024
e_step_buffer_size: 100000
e_step_buffer_update_interval: 100
e_step_loss_window: 1
e_step_min_unique_tokens: 24
e_step_min_unique_w: 0
e_step_start_rollouts: 1024
e_step_unique_w_start: 10000
e_step_update_rollouts: 256
fixed_sd: null
flow_dim_h: 1024
flow_num_layers: 3
length_penalty: 0
lr_discretizer: 0.0001
lr_dynamics: 0.0001
lr_flows: 0.0001
lr_m_step: 0.0001
m_model_cvae_beta: 1.0
m_model_dim_feedforward: 256
m_model_dim_h: 256
m_model_nhead: 8
m_model_num_decoder_layers: 2
m_model_num_encoder_layers: 2
m_model_num_layers: 3
m_model_num_w_embedding_layers: 1
m_model_patch_size: 8
m_model_sd_model_num_layers: 3
m_model_use_mu_as_z0: true
m_model_vae_beta: 1.0
m_step_argmax: false
m_step_batch_size: 256
m_step_buffer_size: 10000
m_step_buffer_update_interval: 100
m_step_max_w_length: false
m_step_p_explore: 0.0
m_step_start_rollouts: 1024
m_step_substrings: true
m_step_temperature: 1.0
m_step_update_rollouts: 256
max_e_steps: 10000
max_log_reward: 10000000000.0
max_mean: 0.25
max_sd: 0.2
max_w_length: 7
min_e_steps: 10000
min_log_reward: -80
min_sd: 0.001
min_w_length: 1
num_m_steps: 2500
num_steps: 20
p_add_exploration_trajectory: 0.3
p_explore_discretizer: 0.1
p_sleep_phase: 0.1
replay_buffer_inv_freq_sequence: true
replay_buffer_inv_freq_token: true
save_checkpoint_every: 100000
save_dir: ./rundata_dsprites/dsprites_500_ref
save_prefix: em
score_weight: 1
sd_multiplier: 1
seed: 0
start_e_steps: 0
start_m_steps: 0
t_dependent_backward: true
t_dependent_forward: false
vocab_group_size: null
vocab_size: 24
z0_dependent_backward: true
z0_dependent_discretizer: false
z0_dependent_forward: false
zT_max_mean: null
